name: Secret in Build Log

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      
      - name: harden-runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with: 
          egress-policy: audit

      - name: Extract and use GCP private key
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          # Extracting the private key from the GCP service account key
          PRIVATE_KEY=$(echo $GCP_SERVICE_ACCOUNT_KEY | jq -r '.private_key')
          
          # Simulate using the private key
          echo "Using the private key for some operation"
          
          # Log the private key (simulating a mistake)
          echo "GCP Private Key: $PRIVATE_KEY"

      - name: Run a script
        run: |
          sleep 2
